export class StudentDetail {
    id:Number;
    sssmid:String;
    familyId:String;
    aadharNumber:String;
    nominationNumber:String;
    category:String;
    categoryName:String;
    religion:String;
    fathersOccupation:String;
    totalIncome:String;
    physicallyDisabled:String;
    physicallyDisabledType:String;
    physicallyDisabledPercentage:String;
    rationCard:String;
    rationCardNumber:String;
    rationCardIssueDate:String;
    fatherName:String;
	motherName:String;
}